version: "3"
services:
  api:
    build:
      context: ./APIMock
    ports:
      - "5000:5000"

  angular-app:
    build:
      context: ./frontend
    ports:
      - "80:80"

  postgres:
    build:
      context: ./Database
    environment:
      POSTGRES_DB: SEII_LLM_Frontend
      #POSTGRES_USER: chatUser
      POSTGRES_PASSWORD: chatPassword123!
    ports:
      - "8889:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  database-api:
    build:
      context: ./DatabaseAPI
    ports:
      - "8888:8888"   

volumes:
  postgres_data:
