version: "3"
services:
  api:
    build:
      context: ./APIMock
    ports:
      - "5000:5000"

  angular-app:
    build:
      context: ./frontend
    ports:
      - "80:80"

#comment out reverse proxy, probably only needed to serve to web in a prod env
  # nginx:
  #   build:
  #     context: ./ReverseProxy
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api
  #     - angular-app
# comment out database for now to speed up build, not implemented
  # postgres:
  #   build:
  #     context: ./Database
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   ports:
  #     - "5432:5432"
