version: "3"
services:
  api:
    build:
      context: ./APIMock
    ports:
      - "5000:5000"

  angular-app:
    build:
      context: ./frontend
    ports:
      - "80:80"

  postgres:
    build:
      context: ./Database
    environment:
      POSTGRES_DB: SEII_LLM_Frontend
      POSTGRES_USER: chatUser
      POSTGRES_PASSWORD: chatPassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

#comment out reverse proxy, probably only needed to serve to web in a prod env
  # nginx:
  #   build:
  #     context: ./ReverseProxy
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api
  #     - angular-app      

volumes:
  postgres_data:
